name: "SmartShunt-Serial-MQTT-HA"
description: "Victron SmartShunt USB Serial To MQTT Home Assistant Addon"
version: "1.0.0"
slug: "smartshunt_serial"
url: "https://github.com/Glimmer90/SmartShunt-Serial-MQTT-HA"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
usb: true
uart: true
options:
  serial_port: "/dev/ttyUSB0"
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: "homeassistant"
  mqtt_password: ""
schema:
  serial_port: device(subsystem=tty)
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: password?
